Proyecto03/config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  #Ruta principal
  root 'main#index'

  #Rutas directas o estáticas
  get 'sessions/new'
  get 'main/index'
  get 'estudiantes/new'
  get 'maestro_sessions/new'
  get 'logout' => 'main#index'
  
  #Rutas estudiantes
  get 'registro' => 'estudiantes#new'  
  get 'estudiantes' => 'estudiantes#index'
  post 'registro' => 'estudiantes#new'
  get 'estudiantes/:estudiantes_id/estadisticas' => 'estudiantes#estadisticas', :as => :estadisticas
  
  #Rutas de los controladores de maestros
  get 'maestro_sessions/new'
  get 'maestros/new'
  get 'maestros_registro' => 'maestros#new'  
  get 'maestros' => 'maestros#index'
  get 'maestros/:maestros_id/aprobar' => 'maestros#aprobar', :as => :aprobar_maestro
  get 'maestros/:maestros_id/env_cor_act' => 'maestros#env_cor_act', :as => :env_cor_act_maestro

  #Rutas para sesiones
  get 'login' => 'sessions#new'
  get 'maestro_login' => 'maestro_sessions#new'
  post 'maestro_login' => 'maestro_sessions#create'
  delete 'maestro_logout' => 'maestro_sessions#destroy'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #Rutas para comentarios
  get 'maestros/:maestros_id/comentarios/:comentarios_id/reportar' => 'comentarios#reportar', :as => :reportar_comentario
  get 'maestros/:maestros_id/comentarios/:comentarios_id/quitar_reporte' => 'comentarios#quitar_reporte', :as => :quitar_reporte_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id/responder' => 'comentarios#responder', :as => :responder_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id' => 'comentarios#edit'

  
  #Rutas para manejar ayudantes
  get 'maestros/:maestros_id/ayudantes_new' => 'estudiantes#ayudante_nuevo', :as => :ayudante_nuevo
  get 'maestros/:maestros_id/ayudantes_delete' => 'ayudantias#ayudante_destroy', :as => :ayudante_eliminar
  get 'maestros/nuevo_ayudante' => 'ayudantias#ayudantes_create', :as => :nuevo_ayudante
  get 'estudiantes/:estudiantes_id/baja_ayudante' => 'ayudantias#baja_ayudante', :as => :baja_ayudante
  get 'estudiantes/:estudiantes_id/mantener_ayudante' => 'ayudantias#mantener_ayudante', :as => :mantener_ayudante


  #Métodos que nos dan las rutas para cada controlador
  resources :estudiantes
  resources :activacion_cuentas, only: [:edit]
  resources :maestro_activacion_cuentas, only: [:edit]
  resources :comentarios, only: [:create, :destroy, :show]
  resources :ayudantias
  resources :maestros
  #Rutas de comentarios anidadas en maestros
  resources :maestros do
    resources :comentarios
  end
end

Proyecto03/app/models/estudiante.rb
# -*- coding: utf-8 -*-
class Estudiante < ActiveRecord::Base
  has_many :comentarios, dependent: :destroy
  attr_accessor :remember_token, :activacion_token
  before_save :downcase_correo
  before_create :crear_activacion_digest
  before_save { self.correo = correo.downcase }
  validates(:nombre, presence: true)
  validates(:correo, presence: true, uniqueness: { case_sensitive: false} )
  apply_simple_captcha
  has_secure_password
  validates(:password, length: { minimum: 6 }, allow_blank: true )

  #Definimos un nuevo token para seguridad del estudiante
  def Estudiante.new_token
    SecureRandom.urlsafe_base64
  end

  #Definimos la búsqueda de un estudiante con un nombre en común
  def Estudiante.search(query)
    where("nombre like ?", "%#{query}%")
  end

  #Buscamos a ayudantes con cierto nombre
  def Estudiante.search_ayudante(query)
    where("nombre like ?", "%#{query}%")
  end
  
  #Método para encriptar la contraseña
  def Estudiante.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end

  #Método para rcordar a un estudiante.
  def remember
    self.remember_token = Estudiante.new_token
    update_attribute(:remember_digest, Estudiante.digest(remember_token))
  end

  #Método para identificar a un estudiante
  def authenticated?(atributo, token)
    digest = send("#{atributo}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  #Método para olvidar a un estudiante
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #Método para activar a un estudiante y modificar su status
  def activar
    update_attribute(:activado, true)
    update_attribute(:activado_a, Time.zone.now)
  end

  #Método para enviar un correo de activación
  def enviar_correo_activacion
    EstudianteMailer.cuenta_activacion(self).deliver_now
  end


  #Privados:
  private

  #Convierte el correo a downcase
  
  def downcase_correo
    self.correo = correo.downcase
  end

  #Crea y asigna un número de activación.
  def crear_activacion_digest
    self.activacion_token = Estudiante.new_token
    self.activacion_digest = Estudiante.digest(activacion_token)
  end
end

Proyecto03/app/controllers/estudiantes_controller.rb
# coding: utf-8
AA# -*- coding: utf-8 -*-
class EstudiantesController < ApplicationController
  respond_to :html, :json, :js
  before_action :es_un_usuario, only: [:edit, :update, :destroy, :show]
  before_action :es_el_usuario, only: [:edit, :update]
  before_action :es_admin, only: [:destroy, :estadisticas] 

  #Método para mostrar el perfil del estudiante
  def show
    @estudiante = Estudiante.find(params[:id])
  end

  #Método para registrar un estudiante nuevo
  def create
    @estudiante = Estudiante.new(estudiante_params)
    if (Estudiante.where("correo LIKE ?", "#{@estudiante.correo}@ciencias.unam.mx")).first == nil
      @estudiante.update_attribute(:correo, @estudiante.correo+"@ciencias.unam.mx")
      if @estudiante.save_with_captcha
        log_in @estudiante
        @estudiante.enviar_correo_activacion
        flash.now[:info] = "Por favor, revisa tu correo para activar tu cuenta."
        log_out
        respond_with @estudiante do |format|
          format.html {redirect_to registro_path, notice: "Espera tu correo para activar y acceder a tu cuenta. Posiblemente tu correo llegue a spam. Te esperamos pronto"}
        end
      else
        render 'new'
      end
    else
      respond_with @estudiante do |format|
        format.html {redirect_to registro_path, notice: "Correo repetido"}
      end
    end
  end
  
  #Método para crear un nuevo estudiante en la base
  def new
    @estudiante = Estudiante.new
  end
  
  #Método para editar los datos del estudiante
  def edit
    @estudiante = Estudiante.find(params[:id])
  end

  #Método para actualizar los datos del estudiante
  def update
    @estudiante = Estudiante.find(params[:id])
    if @estudiante.update_attributes(estudiante_params)
      flash[:succes] = "Perfil actualizado"
      redirect_to @estudiante
    else
      render 'edit'
    end
  end
  
  #Método auxiliar para saber si es el usuario quien manda a llamar a un controlador
  def es_el_usuario
    @estudiante = Estudiante.find(params[:id])
    redirect_to(root_url) unless @estudiante == estudiante_actual
  end

  #Método auxiliar para saber si es un usuario de la base
  def es_un_usuario
    unless conectado?
      flash[:danger] = "Favor de iniciar sesión"
      redirect_to login_url
    end
  end

  #Método para mostrar en una lista los alumnos que existen
  def index
    if params[:search]
      @estudiantes = Estudiante.search(params[:search]).paginate(page: params[:page])
    else
      if estudiante_actual.activado
        @estudiantes = Estudiante.paginate(page: params[:page])
      else
        redirect_to login_url
      end
    end
  end
  
  #Método para crear un nuevo ayudante
  def ayudante_nuevo
    @maestro = Maestro.find(params[:maestro_id])
    if params[:search_ayudante]
      @estudiantes = Estudiante.search(params[:search_ayudante]).paginate(page: params[:page])
    else      
      @estudiantes = Estudiante.paginate(page: params[:page])
    end
  end

  #Método para eliminar una estudiante
  def destroy
    Estudiante.find(params[:id]).destroy
    flash[:succes] = "Estudiante eliminado"
    redirect_to estudiantes_url
  end

  #Método para activar un estudiante y hacerlo válido
  def activar
    update_attribute(:activado, true)
    update_attribute(:activado_a, Time.zone.now)
  end

  #Método auxiliar en la activación del estudiante por correo
  def enviar_correo_activacion
    EstudianteMailer.cuenta_activacion(self).deliver_now
  end

  #Método que saca una pequeña coleacción de los asuntos por hacer del aministrador
  def estadisticas
    @estudiante = Estudiante.find(params[:estudiantes_id])
    @comentarios = (Comentario.where("warning = ?", true)).paginate(page: params[:page], per_page: 4)
    @maestros = (Maestro.where("aprobado = ?", false)).paginate(page: params[:page], per_page: 8)
    @ayudantes = (Ayudantia.where("peticion_eliminar = ?", true)).paginate(page: params[:page], per_page: 10)
    @no_activados = (Maestro.where("correo_enviado = ?", false)).paginate(page: params[:page], per_page: 8)
  end

  #Métodos privados para manejo de estudiantes.
  private
  
  #Método para manejar parámetros fuertes.
  def estudiante_params
    params.require(:estudiante).permit(:nombre, :correo, :password,
                                 :password_confirmation, :captcha, :captcha_key)
  end

  #método para saer si un estudiante tiene permisos de administrador
  def es_admin
    redirect_to(root_url) unless estudiante_actual.admin?
  end
end

Proyecto03/app/helpers/estudiantes_helper.rb
# -*- coding: utf-8 -*-
module EstudiantesHelper
  
  #Método auxiliar para saber si es administrador o no un estudiante.
  def es_admin
    redirect_to(root_url) unless estudiante_actual.admin?
  end
  
  
end

Proyecto03/app/views/estudiantes/ayudante_nuevo.html.erb
<!DOCTYPE html>
<html lang="en">
<%= favicon_link_tag 'favicon2.ico' %>
<title>Estudiantes | El prometeo</title>
<%= stylesheet_link_tag "estilos.css" %>
    <%= stylesheet_link_tag "bootstrap.min.css" %>
    <%= favicon_link_tag 'favicon2.ico' %>
<body>
<%= render 'layouts/header' %>
<%= link_to "Atrás", @maestro %>
<h2>Estudiantes</h2>

<div id="bus">
  <%= form_tag ayudante_nuevo_path(@maestro), :method => "get", id: "search-form" do %>
  <%= hidden_field_tag :maestro_id, @maestro.id %>
  <%= text_field_tag :search_ayudante, params[:search_ayudante], id: "searchbox", placeholder: " Buscar" %>
  <%= submit_tag "Buscar",:class => "btn btn-success", id: "searchbutton", :name => nil %>
  <% end %>       
</div>
<div class="pag"><%= will_paginate %></div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
  	<ul class="estudiantes">
	  <% @estudiantes.each do |estudiante| %>
	  <li> 
	    <%= estudiante.nombre %>
	    <% if !(Ayudantia.where("maestro_id = ? AND estudiante_id = ?", @maestro.id, estudiante.id).count > 0) %>
	    | <%= link_to "Agregar ayudante a profesor "+@maestro.nombre, nuevo_ayudante_path(estudiante: estudiante, maestro_id: @maestro.id) %>
	    <% elsif conectado? && estudiante_actual.admin? %>
	    | <%= link_to "Eliminar ayudante", ayudante_eliminar_path(estudiante, :estudiante_id => estudiante, :maestro_id => @maestro.id), data: { confirm: "¿Estás seguro?" } %>
	    <% end %>
	  </li>
	  <% end %>
	</ul>
  </div>
  <div class="col-md-4"></div>
</div>
<div class="pag"><%= will_paginate %></div>
</body>
<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js" %>
    <%= javascript_include_tag"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"%>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
</html>

Proyecto03/app/views/estudiantes/edit.html.erb
<%= stylesheet_link_tag "estilos.css" %>
<%= stylesheet_link_tag "bootstrap.min.css" %>
<%= favicon_link_tag 'favicon2.ico' %>
<!--Formulario registrarse-->
<%= render 'layouts/header' %>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h3 class="centerh3">Configuración</h3>
        <%= form_for(@estudiante) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :nombre %>
        <%= f.text_field :nombre, class: 'form-control' %>

        <%= f.label :correo %>
        <%= f.text_field :correo, class: 'form-control'  %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control'  %>

        <%= f.label :password_confirmation, 'Confirmation'  %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>

        <%= f.submit "Guardar cambios", class: "btn btn-success btn-lg btn-block" %>
        <% end %>	
    </div>
    <div class="col-md-4"></div>
</div>

Proyecto03/app/views/estudiantes/estadisticas.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= favicon_link_tag 'favicon2.ico' %>
  <title>Pendientes, reportes y por hacer | El prometeo</title>
  <%= stylesheet_link_tag "estilos.css" %>
  <%= stylesheet_link_tag "bootstrap.min.css" %>
  <%= favicon_link_tag 'favicon2.ico' %>
  <body>
    <%= render 'layouts/header' %>
    <h2>Comentarios reportados</h2>
    <section id="prof" data-no-turbolink>
    <%= render @comentarios %>
    <div class="pag">
      <%= will_paginate @comentarios %>
      </div>
    </section>
    <h2>Maestros no aprobados</h2>
    <section id="contenido">
      <% @maestros.each do |maestro| %>
      <article class="item">
	<!--<figure class="imagen_item">
	    <img src="cuBlur.jpg"/>
	</figure>-->
	<h3>
	  <%= link_to maestro.nombre, maestro %>
	  | <%= link_to "Eliminar", maestro, method: :delete, data: { confirm: "¿Estás seguro?" } %>
	  | <%= link_to "Aprobar", aprobar_maestro_path(maestro, :maestro_id => maestro.id, :estudiante_id => @estudiante.id ), data: { confirm: "¿Desea aprobar a este maestro?" } %> 
  </h3>
	  
	  
	  <div class="categoria">				
	    <P>Profesor<p>
	  </div>
      </article>
      <% end %>
    </section>
    
    <div class="pag">
      <%= will_paginate @maestros %>
    </div>    
    <h2>Ayudantes registrados que quiere darse de baja de un profesor</h2>    
    <div class="pag"><%= will_paginate @ayudantes %></div>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
  	<ul class="estudiantes">
	  <% @ayudantes.each do |ayudante| %>
	  <li> 
	    <%= Estudiante.find(ayudante.estudiante_id).nombre %>
	    <% if conectado? && estudiante_actual.admin? %>
	    | <%= link_to "Eliminar ayudante del profesor "+Maestro.find(ayudante.maestro_id).nombre, ayudante_eliminar_path(Estudiante.find(ayudante.estudiante_id), :estudiante_id => ayudante.estudiante_id, :maestro_id => ayudante.maestro_id), data: { confirm: "¿Estás seguro?" } %>
	    |<%= link_to "Eliminar solicitud de baja", mantener_ayudante_path((ayudante.estudiante_id), :maestro_id => ayudante.maestro_id,  :estudiante_id => ayudante.estudiante_id), data: {Confirm: "¿Estás seguro?" } %>	    
	    <% end %>
	  </li>
	  <% end %>
	</ul>
      </div>
      <div class="col-md-4"></div>
    </div>
    <div class="pag"><%= will_paginate @ayudantes %></div>
    
    <h2>Profesores que no se les ha enviado correo electronico</h2>    
    <section id="contenido">
      <% @no_activados.each do |maestro| %>
      <article class="item">
	<!--<figure class="imagen_item">
	    <img src="cuBlur.jpg"/>
	</figure>-->
	<h3>
	  <%= link_to maestro.nombre, maestro %>
	  | <%= link_to "Eliminar", maestro, method: :delete, data: { confirm: "¿Estás seguro?" } %>	  
	  | <%= link_to "Enviar correo a "+maestro.correo, env_cor_act_maestro_path(maestro, :maestro_id => maestro.id, :estudiante_id => @estudiante.id )%> 
	  <h5>MAESTRO NO APROBADO  </h5></h3>  
	  <div class="categoria">				
	    <P>Profesor<p>
	  </div>
      </article>
      <% end %>
    </section>
    
    <div class="pag">
      <%= will_paginate @no_activados %>
    </div>    


  </body>
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js" %>
  <%= javascript_include_tag"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</html>

Proyecto03/app/views/estudiantes/index.html.erb
<!DOCTYPE html>
<html lang="en">
<%= favicon_link_tag 'favicon2.ico' %>
<title>Estudiantes | El prometeo</title>
<%= stylesheet_link_tag "estilos.css" %>
    <%= stylesheet_link_tag "bootstrap.min.css" %>
    <%= favicon_link_tag 'favicon2.ico' %>
<body>
<%= render 'layouts/header' %>

<h2>Estudiantes</h2>

<div id="bus">
  <%= form_tag estudiantes_path, :method => "get", id: "search-form" do %>
  <%= text_field_tag :search, params[:search], id: "searchbox", placeholder: " Buscar" %>
  <%= submit_tag "Buscar",:class => "btn btn-success", id: "searchbutton", :name => nil %>
  <% end %>       
</div>
<div class="pag"><%= will_paginate %></div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
  	<ul class="estudiantes">
	  <% @estudiantes.each do |estudiante| %>
	  <li> 
	    <%= link_to estudiante.nombre, estudiante %>
	    <% if conectado? && estudiante_actual.admin? && !es_estudiante_actual?(estudiante) %>
	    | <%= link_to "Eliminar", estudiante, method: :delete, data: { confirm: "¿Estás seguro?" } %>
	    <% end %>
	  </li>
	  <% end %>
	</ul>
  </div>
  <div class="col-md-4"></div>
</div>
<div class="pag"><%= will_paginate %></div>
</body>
<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js" %>
    <%= javascript_include_tag"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"%>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
</html>

Proyecto03/app/views/estudiantes/new.html.erb
<% if conectado? %>
<script type="text/javascript">
  window.location.href="/estudiantes/<%= estudiante_actual.id %>"  
</script>
<% elsif maestro_conectado? %>
<script type="text/javascript">
  window.location.href="/maestros/<%= maestro_actual.id %>"  
</script>
<% end %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<%= stylesheet_link_tag "estilos.css" %>
<%= stylesheet_link_tag "bootstrap.min.css" %>
<%= favicon_link_tag 'favicon2.ico' %>

<!--Formulario registrarse-->
  <h2 id="form">Registrarse</h2>
  <%= form_for(@estudiante) do |f| %>
  <%= render 'shared/error_messages' %>
  <ul>
  <% flash.each do |key, value| %>
    <li><div class="flash <%= key %>"><%= value %></div></li>
<% end %>
</ul>
    <div class="form-group">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <%= f.label :nombre %>
          <%= f.text_field :nombre, class: 'form-control' %>
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <%= f.label :correo %>
          <%= f.text_field :correo, class: 'form-control'  %><span class="input-group-addon">@ciencias.unam.mx</span>
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control'  %>
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <%= f.label :password_confirmation, 'Repite la contraseña'  %>
          <%= f.password_field :password_confirmation, class: 'form-control'  %>
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
           <%= show_simple_captcha(:object=>"estudiante") %> 
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <%= f.submit "Registrarse", class: "btn btn-success btn-lg btn-block regBtn" %> 
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
  <% end %>


  <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js" %>
  <%= javascript_include_tag "boostrap.min"  %>

Proyecto03/app/views/estudiantes/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title><%= @estudiante.nombre %> | Pregúntale a Prometeo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag "estilos.css" %>
    <%= stylesheet_link_tag "bootstrap.min.css" %>
    <%= favicon_link_tag 'favicon2.ico' %>
  </head>
  <body>
    <header id="welcome">
    <% if !flash[:success].blank? %>
    <div class="alert alert-success" id="comAlert" role="alert">
    	<ul>
  			<% flash.each do |key, value| %>
    		<li><div class="flash <%= key %>"><%= value %></div></li>
			<% end %>
  		</ul>
  	</div>
  	<% end %>
      <h1>El Prometeo</h1>
      <% if conectado? && (estudiante_actual.id != @estudiante.id) %>
      <h5>(Perfil de <%= @estudiante.nombre %>)</h5>
      <% end %>
      <%= form_tag maestros_path, :method => "get", id: "search-form" do %>
      <%= text_field_tag :search, params[:search], id: "searchbox", placeholder: " Buscar" %>
      <%= submit_tag "Buscar", id: "searchbutton", :name => nil %>
      <% end %>       
    </header>
    <%= render 'layouts/header' %>
    
    <section id="contenido">
      <% if Ayudantia.ayudados_por(@estudiante).count > 0 %>
      <h2>ES AYUDANTE DE:</h2>
      <% end %>
      <!--<ul class="nav nav-pills">
	<li role="presentation"><a href="#">A</a></li>
	<li role="presentation"><a href="#">B</a></li>
	<li role="presentation"><a href="#">C</a></li>
	<li role="presentation"><a href="#">D</a></li>
	<li role="presentation"><a href="#">E</a></li>
	<li role="presentation"><a href="#">F</a></li>
	<li role="presentation"><a href="#">G</a></li>
	<li role="presentation"><a href="#">H</a></li>
	<li role="presentation"><a href="#">I</a></li>
	<li role="presentation"><a href="#">J</a></li>
	<li role="presentation"><a href="#">K</a></li>
	<li role="presentation"><a href="#">L</a></li>
	<li role="presentation"><a href="#">M</a></li>
	<li role="presentation"><a href="#">N</a></li>
	<li role="presentation"><a href="#">Ñ</a></li>
	<li role="presentation"><a href="#">O</a></li>
	<li role="presentation"><a href="#">P</a></li>
	<li role="presentation"><a href="#">Q</a></li>
	<li role="presentation"><a href="#">R</a></li>
	<li role="presentation"><a href="#">S</a></li>
	<li role="presentation"><a href="#">T</a></li>
	<li role="presentation"><a href="#">U</a></li>
	<li role="presentation"><a href="#">V</a></li>
	<li role="presentation"><a href="#">W</a></li>
	<li role="presentation"><a href="#">X</a></li>
	<li role="presentation"><a href="#">Y</a></li>
	<li role="presentation"><a href="#">Z</a></li>
      </ul>-->
      <a href="#">
	<% Ayudantia.ayudados_por(@estudiante).each do |ayudado| %>
		<article class="item">
			<!--<figure class="imagen_item">
				<img src="cuBlur.jpg"/>
			</figure>-->
			
			<h3>
				<%= link_to ayudado.nombre, ayudado %> |				
			</h3>
			<% if @estudiante.id == estudiante_actual.id %>
			<h6><%= link_to "Pedir dar de baja", baja_ayudante_path((@estudiante.id), :maestro_id => ayudado.id, :id => @estudiante.id, :estudiante_id => @estudiante.id), data: {Confirm: "¿Estás seguro? (Se revisará tu caso por un administrador)" } %></h6>
			<% end %>
			<div class="categoria">				
				<P>Profesor<p>
			</div>
		</article>
		<% end %>
	</a>
      <% if Comentario.califico_a(@estudiante).count > 0 %>
      <h2>HA CALIFIADO A:</h2>
      <% end %>
	<a href="#">
	<% Comentario.califico_a(@estudiante).each do |calificado| %>
		<article class="item">
			<!--<figure class="imagen_item">
				<img src="cuBlur.jpg"/>
			</figure>-->
			
			<h3>
				<%= link_to calificado.nombre, calificado %>
			</h3>	
			<div class="categoria">				
				<P>Profesor<p>
			</div>
		</article>
		<% end %>
	</a>
	<a href="#">      
    </section>
    <footer>
      <p>Pagina realizada por estudiantes para estudiantes</p>
      <%= @estudiante.nombre %>, <%= @estudiante.correo %>
    </footer>
    <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js" %>
    <%= javascript_include_tag"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"%>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </body>
</html>