Proyecto03/config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  #Ruta principal
  root 'main#index'

  #Rutas directas o estáticas
  get 'sessions/new'
  get 'main/index'
  get 'estudiantes/new'
  get 'maestro_sessions/new'
  get 'logout' => 'main#index'
  
  #Rutas estudiantes
  get 'registro' => 'estudiantes#new'  
  get 'estudiantes' => 'estudiantes#index'
  post 'registro' => 'estudiantes#new'
  get 'estudiantes/:estudiantes_id/estadisticas' => 'estudiantes#estadisticas', :as => :estadisticas
  
  #Rutas de los controladores de maestros
  get 'maestro_sessions/new'
  get 'maestros/new'
  get 'maestros_registro' => 'maestros#new'  
  get 'maestros' => 'maestros#index'
  get 'maestros/:maestros_id/aprobar' => 'maestros#aprobar', :as => :aprobar_maestro
  get 'maestros/:maestros_id/env_cor_act' => 'maestros#env_cor_act', :as => :env_cor_act_maestro

  #Rutas para sesiones
  get 'login' => 'sessions#new'
  get 'maestro_login' => 'maestro_sessions#new'
  post 'maestro_login' => 'maestro_sessions#create'
  delete 'maestro_logout' => 'maestro_sessions#destroy'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #Rutas para comentarios
  get 'maestros/:maestros_id/comentarios/:comentarios_id/reportar' => 'comentarios#reportar', :as => :reportar_comentario
  get 'maestros/:maestros_id/comentarios/:comentarios_id/quitar_reporte' => 'comentarios#quitar_reporte', :as => :quitar_reporte_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id/responder' => 'comentarios#responder', :as => :responder_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id' => 'comentarios#edit'

  
  #Rutas para manejar ayudantes
  get 'maestros/:maestros_id/ayudantes_new' => 'estudiantes#ayudante_nuevo', :as => :ayudante_nuevo
  get 'maestros/:maestros_id/ayudantes_delete' => 'ayudantias#ayudante_destroy', :as => :ayudante_eliminar
  get 'maestros/nuevo_ayudante' => 'ayudantias#ayudantes_create', :as => :nuevo_ayudante
  get 'estudiantes/:estudiantes_id/baja_ayudante' => 'ayudantias#baja_ayudante', :as => :baja_ayudante
  get 'estudiantes/:estudiantes_id/mantener_ayudante' => 'ayudantias#mantener_ayudante', :as => :mantener_ayudante


  #Métodos que nos dan las rutas para cada controlador
  resources :estudiantes
  resources :activacion_cuentas, only: [:edit]
  resources :maestro_activacion_cuentas, only: [:edit]
  resources :comentarios, only: [:create, :destroy, :show]
  resources :ayudantias
  resources :maestros
  #Rutas de comentarios anidadas en maestros
  resources :maestros do
    resources :comentarios
  end
end

Proyecto03/app/controllers/maestro_sessions_controller.rb
# -*- coding: utf-8 -*-
class MaestroSessionsController < ApplicationController
  #Método para crear una nueva sesión de maestros.
  def new
  end

  #Crea una sesión se maestros
  def create
    maestro = Maestro.find_by(correo: (params[:maestro_session][:correo]+"@ciencias.unam.mx").downcase)
    if maestro && maestro.authenticate(params[:maestro_session][:password])
      #if maestro.activado?
        maestro_log_in maestro
        params[:maestro_session][:remember_me] == '1' ? maestro_remember(maestro) : maestro_forget(maestro)
        redirect_to maestro
    else
      flash.now[:danger] = 'Contraseña/correo incorrecto'
      render 'new'
    end
  end
  
  #Cierra la sesión de un maestro
  def destroy
    maestro_log_out if maestro_conectado?
    redirect_to root_url
  end
end

Proyecto03/app/helpers/maestro_sessions_helper.rb
# -*- coding: utf-8 -*-
module MaestroSessionsHelper

  #Inicia sesión al usuario que lo llama
  def maestro_log_in(maestro)
    if maestro.is_a?(Maestro)
      session[:maestro_id] = maestro.id
    else
      session[:maestro_id] = maestro.id
    end
  end

  #Cierra sesión al maestro que lo llama
  def maestro_log_out
    maestro_forget(maestro_actual)
    session.delete(:maestro_id)
    @maestro_actual = nil
  end

  #Método que busca un maestro de la base con un id.
  def busca_maestro(int)
    return Maestro.find(int)
  end

  #Método que olvida a un maestro al cerrar sesión
  def maestro_forget(maestro)
    maestro.forget
    cookies.delete(:maestro_id)
    cookies.delete(:remember_token)
  end

  #Método para recordar al maestro que inició sesión
  def maestro_remember(maestro)
    maestro.remember
    cookies.permanent.signed[:maestro_id] = maestro.id
    cookies.permanent[:remember_token] = maestro.remember_token
  end

  #Regresa el maestro actual
  def maestro_actual
    if(maestro_id = session[:maestro_id])
      @maestro_actual ||= Maestro.find_by(id: maestro_id)
      elsif (maestro_id = cookies.signed[:maestro_id])
      maestro = Maestro.find_by(id: maestro_id)
      if maestro && maestro.authenticated?(:remember, cookies[:remember_token])
       maestro_log_in maestro
       @maestro_actual = maestro
       end
    end
  end

  #Regresa el nombre del maestro
    def nombre_maestro_actual
      @maestro_actual ||= Maestro.find_by(id: session[:maestro_id])
    return @maestro_actual.nombre
  end

  #Metodo para saber si está conectado
  def maestro_conectado?
    !maestro_actual.nil?
  end

  #Método para saber si el maestro que recibe es el maestro actual
  def es_maestro_actual?(maestro)
    maestro == maestro_actual
  end

end

Proyecto03/app/views/maestro_sessions/new.html.erb
<% if conectado? %>
<script type="text/javascript">
  window.location.href="/estudiantes/<%= estudiante_actual.id %>"  
</script>
<% elsif maestro_conectado? %>
<script type="text/javascript">
  window.location.href="/maestros/<%= maestro_actual.id %>"  
</script>
<% end %>
<%= favicon_link_tag 'favicon2.ico' %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<%= stylesheet_link_tag "estilos.css" %>
<%= stylesheet_link_tag "bootstrap.min.css" %>
<h2 id="form">Ingresar (Sesión Maestro)</h2>
<%= render 'shared/error_logins' %>
<%= form_for(:maestro_session, url: maestro_login_path) do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.label :correo %>
        <%= f.text_field :correo, class: 'form-control' %><span class="input-group-addon">@ciencias.unam.mx</span>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>Recordarme en esta computadora</span>
        <% end %>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>  
  <div class="form-group">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.submit "Iniciar sesión", class: "btn btn-success btn-lg btn-block" %>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
  <% end %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <p>¿Nuevo profesor? <%= link_to "Registro", maestros_registro_path %> </p>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <p>¿Estudiante? <%= link_to "Ingresa(Estudiante)", login_path %> </p>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>

</div>
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js" %>
  <%= javascript_include_tag "boostrap.min"  %>