Proyecto03/config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  #Ruta principal
  root 'main#index'

  #Rutas directas o estáticas
  get 'sessions/new'
  get 'main/index'
  get 'estudiantes/new'
  get 'maestro_sessions/new'
  get 'logout' => 'main#index'
  
  #Rutas estudiantes
  get 'registro' => 'estudiantes#new'  
  get 'estudiantes' => 'estudiantes#index'
  post 'registro' => 'estudiantes#new'
  get 'estudiantes/:estudiantes_id/estadisticas' => 'estudiantes#estadisticas', :as => :estadisticas
  
  #Rutas de los controladores de maestros
  get 'maestro_sessions/new'
  get 'maestros/new'
  get 'maestros_registro' => 'maestros#new'  
  get 'maestros' => 'maestros#index'
  get 'maestros/:maestros_id/aprobar' => 'maestros#aprobar', :as => :aprobar_maestro
  get 'maestros/:maestros_id/env_cor_act' => 'maestros#env_cor_act', :as => :env_cor_act_maestro

  #Rutas para sesiones
  get 'login' => 'sessions#new'
  get 'maestro_login' => 'maestro_sessions#new'
  post 'maestro_login' => 'maestro_sessions#create'
  delete 'maestro_logout' => 'maestro_sessions#destroy'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #Rutas para comentarios
  get 'maestros/:maestros_id/comentarios/:comentarios_id/reportar' => 'comentarios#reportar', :as => :reportar_comentario
  get 'maestros/:maestros_id/comentarios/:comentarios_id/quitar_reporte' => 'comentarios#quitar_reporte', :as => :quitar_reporte_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id/responder' => 'comentarios#responder', :as => :responder_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id' => 'comentarios#edit'

  
  #Rutas para manejar ayudantes
  get 'maestros/:maestros_id/ayudantes_new' => 'estudiantes#ayudante_nuevo', :as => :ayudante_nuevo
  get 'maestros/:maestros_id/ayudantes_delete' => 'ayudantias#ayudante_destroy', :as => :ayudante_eliminar
  get 'maestros/nuevo_ayudante' => 'ayudantias#ayudantes_create', :as => :nuevo_ayudante
  get 'estudiantes/:estudiantes_id/baja_ayudante' => 'ayudantias#baja_ayudante', :as => :baja_ayudante
  get 'estudiantes/:estudiantes_id/mantener_ayudante' => 'ayudantias#mantener_ayudante', :as => :mantener_ayudante


  #Métodos que nos dan las rutas para cada controlador
  resources :estudiantes
  resources :activacion_cuentas, only: [:edit]
  resources :maestro_activacion_cuentas, only: [:edit]
  resources :comentarios, only: [:create, :destroy, :show]
  resources :ayudantias
  resources :maestros
  #Rutas de comentarios anidadas en maestros
  resources :maestros do
    resources :comentarios
  end
end

Proyecto03/app/views/layouts/_header.html.erb
<% if conectado? || maestro_conectado? %>
<nav class="navbar navbar-default" data-no-turbolink role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobile">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=
	 <% if conectado? %>
	 <%=  estudiante_path(estudiante_actual.id) %>
	 <% elsif maestro_conectado? %>
	 <%=  maestro_path(maestro_actual.id) %>
	 <% end %>
	 >El Prometeo</a>
    </div>
    <div class="collapse navbar-collapse" data-no-turbolink id="mobile">
      <ul class="nav navbar-nav">
	<% if conectado? %>
        <li><%= link_to "Inicio", estudiante_actual %></li>     
	<% else %>
	<li><%= link_to "Inicio", maestro_actual %></li>     
	<% end %>
	<li><a href=<%= maestros_path %>>Profesores</a></li>
        <li>
          <% if conectado? %>
        <li><%= link_to "Estudiantes", estudiantes_path %></li>
      	<% if estudiante_actual.admin? %>
	<li><%= link_to "Reportes y estadísticas", estadisticas_path(estudiante_actual) %></li>
      	<% end %>

            <% end %>   
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
	<li>
	  <%= form_tag maestros_path, :class =>"navbar-form navbar-left", :method => "get", id: "search-form" do %>

	    <%= text_field_tag :search, params[:search], :class => "form-control", id: "searchbox", placeholder: " Buscar" %>
	  <%= submit_tag "Buscar", class: "btn btn-success", id: "searchbutton", :name => nil %>
	  <% end %>               
	  </li>
	
        <!-- Nombre de ususario --> 
        <li class="dropdown" data-no-turbolink>
          <% if conectado? %>
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= nombre_estudiante_actual %> <span class="caret"></span></a>
	  <% else %>
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= nombre_maestro_actual %> <span class="caret"></span></a>
	  <% end %>
          <ul class="dropdown-menu" role="menu" data-no-turbolink>
	    <% if conectado? %>
            <li><%= link_to "Perfil", estudiante_actual %></li>
	    <li><%= link_to "Estudiantes", estudiantes_path %></li>
      	    <% if estudiante_actual.admin? %>
	    <li><%= link_to "Reportes y estadísticas", estadisticas_path(estudiante_actual) %></li>
      	    <% end %>
            <li><%= link_to "Configuración", edit_estudiante_path(estudiante_actual)%></li>	
            <li class="divider"></li>
            <li><%= link_to "Cerrar sesion", logout_path, method: "delete" %></li>
	    <% else %>
	    <li><%= link_to "Perfil", maestro_actual %></li>
            <li><%= link_to "Configuración", edit_maestro_path(maestro_actual)%></li>	
            <li class="divider"></li>
            <li><%= link_to "Cerrar sesion", maestro_logout_path, method: "delete" %></li>
	    <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% end %>