Proyecto03/config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  #Ruta principal
  root 'main#index'

  #Rutas directas o estáticas
  get 'sessions/new'
  get 'main/index'
  get 'estudiantes/new'
  get 'maestro_sessions/new'
  get 'logout' => 'main#index'
  
  #Rutas estudiantes
  get 'registro' => 'estudiantes#new'  
  get 'estudiantes' => 'estudiantes#index'
  post 'registro' => 'estudiantes#new'
  get 'estudiantes/:estudiantes_id/estadisticas' => 'estudiantes#estadisticas', :as => :estadisticas
  
  #Rutas de los controladores de maestros
  get 'maestro_sessions/new'
  get 'maestros/new'
  get 'maestros_registro' => 'maestros#new'  
  get 'maestros' => 'maestros#index'
  get 'maestros/:maestros_id/aprobar' => 'maestros#aprobar', :as => :aprobar_maestro
  get 'maestros/:maestros_id/env_cor_act' => 'maestros#env_cor_act', :as => :env_cor_act_maestro

  #Rutas para sesiones
  get 'login' => 'sessions#new'
  get 'maestro_login' => 'maestro_sessions#new'
  post 'maestro_login' => 'maestro_sessions#create'
  delete 'maestro_logout' => 'maestro_sessions#destroy'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #Rutas para comentarios
  get 'maestros/:maestros_id/comentarios/:comentarios_id/reportar' => 'comentarios#reportar', :as => :reportar_comentario
  get 'maestros/:maestros_id/comentarios/:comentarios_id/quitar_reporte' => 'comentarios#quitar_reporte', :as => :quitar_reporte_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id/responder' => 'comentarios#responder', :as => :responder_comentario
  #get 'maestros/:maestros_id/comentarios/:comentarios_id' => 'comentarios#edit'

  
  #Rutas para manejar ayudantes
  get 'maestros/:maestros_id/ayudantes_new' => 'estudiantes#ayudante_nuevo', :as => :ayudante_nuevo
  get 'maestros/:maestros_id/ayudantes_delete' => 'ayudantias#ayudante_destroy', :as => :ayudante_eliminar
  get 'maestros/nuevo_ayudante' => 'ayudantias#ayudantes_create', :as => :nuevo_ayudante
  get 'estudiantes/:estudiantes_id/baja_ayudante' => 'ayudantias#baja_ayudante', :as => :baja_ayudante
  get 'estudiantes/:estudiantes_id/mantener_ayudante' => 'ayudantias#mantener_ayudante', :as => :mantener_ayudante


  #Métodos que nos dan las rutas para cada controlador
  resources :estudiantes
  resources :activacion_cuentas, only: [:edit]
  resources :maestro_activacion_cuentas, only: [:edit]
  resources :comentarios, only: [:create, :destroy, :show]
  resources :ayudantias
  resources :maestros
  #Rutas de comentarios anidadas en maestros
  resources :maestros do
    resources :comentarios
  end
end

Proyecto03/app/models/comentario.rb
# -*- coding: utf-8 -*-
class Comentario < ActiveRecord::Base
  belongs_to :estudiante
  belongs_to :maestro
  default_scope -> { order(created_at: :desc) }
  validates :estudiante_id, presence: true
  validates :comentario, presence: true, length: { maximum: 300 }
  validates :maestro_id, presence: true

  #Buscamos a los comentarios de un estudiante
  def Comentario.califico_a(estudiante)
    com = Comentario.where("estudiante_id = ?", estudiante.id).order(:created_at)
    arr = Array.new
    i = 0
    while i < com.count do
      arr.push(Maestro.find(com[i].maestro_id))
      i += 1
    end
    return arr
  end
  
  #Método que nos dice si un estudiante ya calificó a un profesor
  def Comentario.ya_califico(estudiante, maestro)
    com = Comentario.where("estudiante_id = ? AND maestro_id = ?", estudiante.id, maestro.id)
    if com.count > 0
      return true
    else
      return false
    end
  end
end

Proyecto03/app/controllers/comentarios_controller.rb
# -*- coding: utf-8 -*-
class ComentariosController < ApplicationController
  before_action :es_un_usuario, only: [:create, :destroy]

  #Método para crear un comentario nuevo
  def new
    @comentario = Comentario.new
  end

  #Método para editar los elementos del comentario (respuesta)
  def edit
    @comentario = Comentario.find(params[:comentarios_id])
    redirect_to Maestro.find(params[:maestros_id]).path
  end

  #Método para crear un comentario nuevo.
  def create
    @comentario = Comentario.new(comentario_params)
    @maestro = Maestro.find(params[:maestro_id])
    @comentario.maestro_id = @maestro.id
    if @comentario.save
      flash[:success] = "Tu comentario ha sido guardado"
      redirect_to @maestro
    else
      render 'new'
    end
  end

  #Método para actualizar el comentario
  def update
    @comentario = Comentario.find(params[:id])
    @maestro = Maestro.find(params[:maestro_id])
    if @comentario.update_attributes(comentario_params)
      flash[:succes] = "Perfil actualizado"
      redirect_to @maestro
    else
      render 'edit'
    end
  end

  #Método para eliminar un comentario
  def destroy
    @comentario = Comentario.find(params[:id]).destroy
    redirect_to busca_maestro(@comentario.maestro_id)
  end

  #Método para reportar un comentario
  def reportar
    @comentario = Comentario.find(params[:comentario_id])
    @comentario.update_attribute(:warning, true)
    if conectado?
      redirect_to busca_maestro(@comentario.maestro_id)
    elsif maestro_conectado?
      redirect_to maestro_actual
    else
      redirect_to root_path
    end
  end  

  #Método para eliminar el reporte de un comentario previamente reportado
  def quitar_reporte
    @comentario = Comentario.find(params[:comentario_id])
    @comentario.update_attribute(:warning, false)
    if conectado?
      redirect_to busca_maestro(@comentario.maestro_id)
    elsif maestro_conectado?
      redirect_to maestro_actual
    else
      redirect_to root_path
    end
  end  

  #Método para que los profesores puedan responder comentarios
  def responder
    @comentario = Comentario.find(params[:comentario_id])
  end
  
  #Método auxiliar
  def show
    redirect_to root_path
  end
  
  private
  #Método para usar parametros fuertes en los comentarios
  def comentario_params
    params.require(:comentario).permit(:comentario,
                                       :estudiante_id,
                                       :maestro_id,
                                       :semestre,
                                       :materia,
                                       :facilidad,
                                       :ayuda,
                                       :claridad,
                                       :aprobo,
                                       :recursador,
                                       :evaluacion,
                                       :recomendacion,
                                       :ayudante_nombre,
                                       :ayudante_comentario,
                                       :respuesta)
  end
end

Proyecto03/app/helpers/comentarios_helper.rb
module ComentariosHelper

end

Proyecto03/app/views/comentarios/_comentario.html.erb
<section class="comentarios-prof">
  <div class="comment">
    <ul>
      <li>
	<div>
	  Estudiante:
 	</div>
	<% if (conectado? && !es_ayudante_de(comentario.maestro_id)) || (conectado? && estudiante_actual.admin?) %>
	<p><%= link_to comentario.estudiante.nombre, comentario.estudiante %></p>
	<% else %>
<p> Estudiante miembro desde <%= comentario.estudiante.created_at.to_date %></p>
<% end %>
</li>
<li>
  <div>
    Semestre:
  </div>
  <% if comentario.semestre.month < 7 %>
     <p><%= comentario.semestre.year %>-1</p>
     <% else %>
     <p><%= comentario.semestre.year %>-2</p>
     <% end %> 
</li>
<li>
  <div>
	  Materia:
	</div>
	<p><%= comentario.materia %></p>
      </li>
      <li>
	<div>
	  Facilidad:
	</div>
	<p><%= comentario.facilidad %></p>
      </li>
      <li>
	<div>
	  Ayuda:
	</div>
	<p><%= comentario.ayuda %></p>
      </li>
      <li>
	<div>
	  Claridad:
	</div>
	<p><%= comentario.claridad %></p>
      </li>
      <li>
	<div>
	  Aprobó:
	</div>
	<% if comentario.aprobo == true %>
	<p>Si</p>
	<% else %>
	<p>No</p>
	<% end %>
      </li>
      <li>
	<div>
	  Recursador:
	</div>
	<% if comentario.recursador == true %>
	<p>Si</p>
	<% else %>
	<p>No</p>
	<% end %>
      </li>
      <li>
	<div>
	  Total:
	</div>
	<p>10</p>
      </li>
      <li>
	<div>
	  ¿Lo recomienda?
	</div>
	<% if comentario.recomendacion == true %>
	Si
	<% else %>
	<p>No</p>
	<% end %>
      </li>
      
    </ul>
    
    <label>Métodos de evaluación:</label>
    <%= comentario.evaluacion %>
    <label>Comentario:</label>
    
    <p class="text">
      <% if comentario.warning %>
      El comentario fue reportado y está esperando revisión.
      <% else %>
      <%= comentario.comentario %>
      <% if !(comentario.ayudante_comentario == nil) %>
      <p><label>Nombre del ayudante:</label>    
	<%= comentario.ayudante_nombre %> </p>
      <label>Comentario hacerca del ayudante:</label>
      <%= comentario.ayudante_comentario %>
      <% end %>
      <% end %>
    <% if comentario.warning && (conectado? && estudiante_actual.admin?)%>
    COMENTARIO REPORTADO: <%= comentario.comentario %>
    <% end %>
    </p>
    <p>Publicado hace <%= time_ago_in_words(comentario.created_at) %>.</p>

    <% if comentario.respuesta != nil %>
    <h5>RESPUESTA DEL PROFESOR:</h5>
      <p><%= comentario.respuesta %></p>
      <% elsif maestro_conectado? %>
      
      <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#responder">Responder</button>
      <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js" %>
      <%= javascript_include_tag"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"%>
      <%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>      
      <div class="modal fade" id="responder"  data-backdrop="false"> 
	<div class="modal-dialog">
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	      <h4 class="modal-title" id="exampleModalLabel">Responder comentario</h4>
	    </div>	
	    <div class="modal-body">	      
	      <%= form_for [Maestro.find(comentario.maestro_id), comentario] do |f| %>
	      
	      <%= f.label :respuesta %>
	      <%= f.text_area :respuesta, class: 'form-control' %>
	      <div class="modal-footer">
		<%= f.submit "Responder", class: "btn btn-success btn-lg btn-block" %>
	      </div>
	      <% end %>	
	      
	    </div>	    
	  </div>
	</div>
      </div>
      
    <% end %>
    <% if comentario.warning && (conectado? && estudiante_actual.admin?)%>
    <p><%= link_to "Quitar reporte", quitar_reporte_comentario_path(busca_maestro(comentario.maestro_id), comentario,:maestro_id => comentario.maestro_id, :comentario_id => comentario.id), data: { confirm: "¿Ha revisado que el contenido del comentario no sea inapropiado?" } %></p>

<% else %>
<p><%= link_to "Reportar un comentario", reportar_comentario_path(busca_maestro(comentario.maestro_id), comentario, :maestro_id => comentario.maestro_id, :comentario_id => comentario.id), data: { confirm: "¿Desea reportar este comentario como inapropiado?" } %></p>
<% end %>
<% if conectado? && estudiante_actual.admin? %>
<p><%= link_to "Eliminar comentario", comentario, method: :delete, data: { confirm: "¿Estás seguro de eliminar el comentario?" }  %></p>
<% end %>
</div>
</section>

Proyecto03/app/views/comentarios/responder.html.erb
<%= stylesheet_link_tag "estilos.css" %>
<%= stylesheet_link_tag "bootstrap.min.css" %>
<%= favicon_link_tag 'favicon2.ico' %>
<!--Formulario registrarse-->
<%= render 'layouts/header' %>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h3 class="centerh3">Configuración</h3>
        <%= form_for [@maestro, @comentario], :url => @maestro_url do |f| %>

        <%= f.label :respuesta %>
        <%= f.text_area :respuesta, class: 'form-control' %>

        <%= f.submit "Responder", class: "btn btn-success btn-lg btn-block" %>
        <% end %>	
    </div>
    <div class="col-md-4"></div>
</div>